language: node_js
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start -screen 0 1024x768x24 > /dev/null 2>&1 &"
  - sleep 5 # give xvfb some time to start
script:
  - npm run ci
node_js:
  - "6"
  - "5"
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

